version: "3.5"
services:
    postgres:
        image: "postgres:10"
        container_name: "postgres"
        restart: "always"
        volumes:
            - "./pgdata:/var/lib/postgresql/data"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=keycloak
            - POSTGRES_DB=keycloak

    keycloak:
        image: quay.io/keycloak/keycloak:21.0
        container_name: "keycloak"
        restart: "always"
        depends_on:
            - "postgres"
        entrypoint: ["/bin/sh","-c","rm --force /opt/keycloak/conf/server.keystore && keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname 'CN=server' -alias server -ext 'SAN:c=DNS:keycloak.localhost,IP:127.0.0.1' -keystore /opt/keycloak/conf/server.keystore && /opt/keycloak/bin/kc.sh start --db postgres --db-url-host postgres --db-username keycloak --db-password keycloak --proxy reencrypt --hostname keycloak.localhost"]
        environment:
            - KEYCLOAK_ADMIN=keycloak
            - KEYCLOAK_ADMIN_PASSWORD=keycloak

    nginx:
        image: "nginx"
        container_name: "nginx"
        restart: "always"
        depends_on:
            - "keycloak"
        volumes:
            - "./certs:/etc/nginx/certs"
            - "./nginx/conf.d:/etc/nginx/conf.d"
        ports:
            - 443:443
#            - 80:80


